Fix -Wtautological-constant-out-of-range-compare.
packages/modules/ImsMedia/service/src/com/android/telephony/imsmedia/lib
/libimsmedia/core/audio/nodes/AudioRtpPayloadDecoderNode.cpp:732:19: error:
result of comparison of constant 8 with expression of type 'kEvsCmrCodeType'
is always true [-Werror,-Wtautological-constant-out-of-range-compare]
   2   732 |          if (cmr_t <  8 )   // cmr_type is 3bit validation.
   3       |            ~~~~~ ^ ~
Remove the check because it is redundant.

packages/modules/ImsMedia/service/src/com/android/telephony/imsmedia/lib
/libimsmedia/core/audio/RtcpXrEncoder.cpp:464:30: error: result of
comparison of constant -1 with expression of type 'uint8_t' (aka 'unsigned
char') is always false [-Werror,-Wtautological-constant-out-of-range-
compare]
   2   464 |     if (ttlReport->ipVersion == -1)
   3       |         ~~~~~~~~~~~~~~~~~~~~ ^  ~~
Re-write the if-then-else conditions to better convey the intent without
triggering this error.

Generated by Gemini.

Test: presubmit
Bug: 72331526
Flag: EXEMPT PURE_REFACTOR
Change-Id: I2829859bb3f6019109113c828bd4c618ed7db9ca